# Generated by Django 3.2 on 2021-04-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssfacts', '0002_body_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='type',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
