# Generated by Django 3.2 on 2021-04-17 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssfacts', '0003_alter_body_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='body',
            name='type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='fact',
            name='body',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ssfacts.body'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
